# This has an example of how you can set up Jenkins through Docker. Note that connecting the agent to
# the main controller requires getting the secret from the controller first, so the agent will
# not be viable until that process is completed
version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  jenkins-agent:
    image: jenkins/inbound-agent
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=worker1
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - JENKINS_SECRET=TBD
    depends_on:
      - jenkins

volumes:
  jenkins_home: